import { PaginationQuery } from "#/@types/misc";
import Audio, { AudioDocument } from "#/models/audio";
import AutoGeneratedPlaylist from "#/models/autoGeneratedPlaylist";
import History from "#/models/history";
import Playlist from "#/models/playlist";
import User from "#/models/users";
import { getUsersPreviousHistory } from "#/utils/helper";
import { Request, Response } from "express";
import moment from "moment";
import { isValidObjectId, ObjectId, PipelineStage, Types } from "mongoose";
import { PipelineCallback } from "stream";

export async function updateFollower(req: Request, res: Response) {
  const { profileId } = req.params;

  let status: "added" | "removed";

  if (!isValidObjectId(profileId))
    return res.status(422).json({ error: "Invalid profile id" });

  const profile = await User.findById(profileId);

  if (!profile) return res.status(404).json({ error: "Profile not found" });

  const alreadyFollowing = await User.findOne({
    _id: profileId,
    followers: req.user.id,
  });

  if (alreadyFollowing) {
    await User.updateOne(
      { _id: profileId },
      { $pull: { followers: req.user.id } }
    );

    status = "removed";
  } else {
    await User.updateOne(
      { _id: profileId },
      { $addToSet: { followers: req.user.id } }
    );

    status = "added";
  }

  if (status === "added") {
    await User.updateOne(
      { _id: req.user.id },
      { $addToSet: { followings: profileId } }
    );
  }

  if (status === "removed") {
    await User.updateOne(
      { _id: req.user.id },
      { $pull: { followings: profileId } }
    );
  }

  res.status(200).json({ status });
}

export async function getUploadedAudios(req: Request, res: Response) {
  const { limit = "20", page = "0" } = req.query as PaginationQuery;

  const data = await Audio.find({ owner: req.user.id })
    .skip(parseInt(limit) * parseInt(page))
    .limit(parseInt(limit))
    .sort("-createdAt");

  const audios = data.map((item) => {
    return {
      id: item._id,
      title: item.title,
      about: item.about,
      file: item.file.url,
      poster: item.poster?.url,
      date: item.createdAt,
      owner: { name: req.user.name, id: req.user.id },
    };
  });

  res.status(200).json({ audios });
}

export async function getPublicUploads(req: Request, res: Response) {
  const { profileId } = req.params;
  const { limit = "20", page = "0" } = req.query as PaginationQuery;

  if (!isValidObjectId(profileId))
    return res.status(422).json({ error: "Invalid profile id" });

  const data = await Audio.find({
    owner: profileId,
  })
    .skip(parseInt(limit) * parseInt(page))
    .limit(parseInt(limit))
    .sort("-createdAt")
    .populate<AudioDocument<{ name: string; _id: ObjectId }>>("owner");

  console.log(data);

  const audios = data.map((item) => {
    return {
      id: item._id,
      title: item.title,
      about: item.about,
      file: item.file.url,
      poster: item.poster?.url,
      date: item.createdAt,
      owner: { name: item.owner.name, id: profileId },
    };
  });

  res.status(200).json({ audios });
}

export async function getPublicProfile(req: Request, res: Response) {
  const { profileId } = req.params;

  if (!isValidObjectId(profileId))
    return res.status(422).json({ error: "Invalid profile id" });

  const user = await User.findById(profileId);
  if (!user) return res.status(404).json({ error: "Profile not found" });

  res.status(200).json({
    user: {
      id: user._id,
      name: user.name,
      avatar: user.avatar?.url,
      followers: user.followers.length,
      followings: user.followings.length,
      createdAt: user.createdAt,
    },
  });
}

export async function getPublicPlaylists(req: Request, res: Response) {
  const { profileId } = req.params;
  const { limit = "20", page = "0" } = req.query as PaginationQuery;

  if (!isValidObjectId(profileId))
    return res.status(422).json({ error: "Invalid profile id" });

  const playlist = await Playlist.find({
    owner: profileId,
    visibility: "public",
  })
    .skip(parseInt(limit) * parseInt(page))
    .limit(parseInt(limit))
    .sort("-createdAt");

  if (!playlist) return res.status(404).json({ playlist: [] });

  res.status(200).json({
    playlist: playlist.map((item) => {
      return {
        id: item._id,
        title: item.title,
        itemsCount: item.items.length,
        visibility: item.visibility,
      };
    }),
  });
}

export async function getRecommendedByProfile(req: Request, res: Response) {
  const user = req.user;

  let matchOptions: PipelineStage.Match = {
    $match: { _id: { $exists: true } },
  };

  if (user) {
    const category = await getUsersPreviousHistory(req);

    if (category.length) {
      matchOptions = {
        $match: { category: { $in: category } },
      };
    }
  }

  const audios = await Audio.aggregate([
    matchOptions,

    { $sort: { "likes.count": -1 } },

    { $limit: 10 },

    {
      $lookup: {
        from: "users",
        localField: "owner",
        foreignField: "_id",
        as: "owner",
      },
    },

    { $unwind: "$owner" },

    {
      $project: {
        _id: 0,
        id: "$_id",
        title: "$title",
        category: "$category",
        about: "$about",
        file: "$file.url",
        poster: "$poster.url",
        owner: { name: "$owner.name", id: "$owner._id" },
      },
    },
  ]);

  res.status(200).json({ audios });
}

export async function getAutoGeneratedPlaylist(req: Request, res: Response) {
  const [result] = await History.aggregate([
    { $match: { owner: req.user.id } },

    { $unwind: "$all" },

    { $group: { _id: "$all.audio", items: { $addToSet: "$all.audio" } } },

    { $sample: { size: 20 } },

    { $group: { _id: null, items: { $push: "$_id" } } },
  ]);

  const title = "Mix 20";

  if (result) {
    await Playlist.updateOne(
      { owner: req.user.id, title },
      { $set: { title, items: result.items, visibility: "auto" } },
      { upsert: true }
    );
  }

  const category = await getUsersPreviousHistory(req);

  let matchOptions: PipelineStage.Match = {
    $match: { _id: { $exists: true } },
  };

  if (category.length) {
    matchOptions = { $match: { title: { $in: category } } };
  }

  const autoPlaylist = await AutoGeneratedPlaylist.aggregate([
    matchOptions,

    { $sample: { size: 4 } },

    {
      $project: {
        _id: 0,
        id: "$_id",
        title: "$title",
        itemsCount: { $size: "$items" },
      },
    },
  ]);

  const playlist = await Playlist.findOne({ owner: req.user.id, title });

  const finalList = autoPlaylist.concat({
    id: playlist?._id,
    title: playlist?.title,
    itemsCount: playlist?.items.length,
  });

  res.status(200).json({ playlist: finalList });
}

export async function getFollowersProfile(req: Request, res: Response) {
  const { limit = "20", page = "0" } = req.query as PaginationQuery;

  const [result] = await User.aggregate([
    { $match: { _id: req.user.id } },

    {
      $project: {
        followers: {
          $slice: [
            "$followers",
            parseInt(page) * parseInt(limit),
            parseInt(limit),
          ],
        },
      },
    },

    { $unwind: "$followers" },

    {
      $lookup: {
        from: "users",
        localField: "followers",
        foreignField: "_id",
        as: "userInfo",
      },
    },

    { $unwind: "$userInfo" },

    {
      $group: {
        _id: null,
        followers: {
          $push: {
            id: "$userInfo._id",
            name: "$userInfo.name",
            avatar: "$userInfo.avatar.url",
          },
        },
      },
    },
  ]);

  if (!result) return res.status(200).json({ followers: [] });

  res.status(200).json({ followers: result.followers });
}

export async function getFollowings(req: Request, res: Response) {
  const { limit = "20", page = "0" } = req.query as PaginationQuery;

  const [result] = await User.aggregate([
    { $match: { _id: req.user.id } },

    {
      $project: {
        followings: {
          $slice: [
            "$followings",
            parseInt(page) * parseInt(limit),
            parseInt(limit),
          ],
        },
      },
    },

    { $unwind: "$followings" },

    {
      $lookup: {
        from: "users",
        localField: "followings",
        foreignField: "_id",
        as: "userInfo",
      },
    },

    { $unwind: "$userInfo" },

    {
      $group: {
        _id: null,
        followings: {
          $push: {
            id: "$userInfo._id",
            name: "$userInfo.name",
            avatar: "$userInfo.avatar.url",
          },
        },
      },
    },
  ]);

  if (!result) return res.status(200).json({ followings: [] });

  res.status(200).json({ followings: result.followings });
}

export async function getFollowersProfilePublic(req: Request, res: Response) {
  const { profileId } = req.params;

  if (!isValidObjectId(profileId))
    return res.status(422).json({ error: "Invalid profile id" });

  const { limit = "20", page = "0" } = req.query as PaginationQuery;

  const [result] = await User.aggregate([
    { $match: { _id: new Types.ObjectId(profileId) } },

    {
      $project: {
        followers: {
          $slice: [
            "$followers",
            parseInt(page) * parseInt(limit),
            parseInt(limit),
          ],
        },
      },
    },

    { $unwind: "$followers" },

    {
      $lookup: {
        from: "users",
        localField: "followers",
        foreignField: "_id",
        as: "userInfo",
      },
    },

    { $unwind: "$userInfo" },

    {
      $group: {
        _id: null,
        followers: {
          $push: {
            id: "$userInfo._id",
            name: "$userInfo.name",
            avatar: "$userInfo.avatar.url",
          },
        },
      },
    },
  ]);

  if (!result) return res.status(200).json({ followers: [] });

  res.status(200).json({ followers: result.followers });
}
