import {
  getAutoGeneratedPlaylist,
  getFollowersProfile,
  getFollowersProfilePublic,
  getFollowings,
  getPublicPlaylists,
  getPublicProfile,
  getPublicUploads,
  getRecommendedByProfile,
  getUploadedAudios,
  updateFollower,
} from "#/controllers/profile";
import { isAuth, isAuthSoft } from "#/middleware/auth";
import { RequestHandler, Router } from "express";

const router = Router();

router.post(
  "/update-follower/:profileId",
  isAuth as RequestHandler,
  updateFollower as RequestHandler
);

router.get(
  "/uploads",
  isAuth as RequestHandler,
  getUploadedAudios as RequestHandler
);

//Public routes
router.get("/uploads/:profileId", getPublicUploads as RequestHandler);

router.get("/info/:profileId", getPublicProfile as RequestHandler);

router.get("/playlists/:profileId", getPublicPlaylists as RequestHandler);

router.get(
  "/recommended",
  isAuthSoft as RequestHandler,
  getRecommendedByProfile as RequestHandler
);

router.get(
  "/auto-generated-playlist",
  isAuth as RequestHandler,
  getAutoGeneratedPlaylist
);

router.get(
  "/followers",
  isAuth as RequestHandler,
  getFollowersProfile as RequestHandler
);

router.get(
  "/followings",
  isAuth as RequestHandler,
  getFollowings as RequestHandler
);

router.get(
  "/followers/:profileId",
  isAuth as RequestHandler,
  getFollowersProfilePublic as RequestHandler
);

export default router;
